Get all pending submissions as doctor
danielaWaldeck95/big_challenge pull request #17
Opened 2023-04-20 15:09 UTC by danielaWaldeck95

Create a new endpoint to retrieve all the pending submissions. This endpoint will be only used by Doctors.

Previous endpoint was adapted in order to retrieve submissions for any kind of user (patient or doctor) allowing filtering. 

Update tests, create new ones and reuse dataset for invalid users.

2023-04-20 15:44 UTC, gianfranco-rocco requested changes

2023-04-20 15:44 UTC, gianfranco-rocco commented on app/Http/Controllers/GetPendingSubmissionsController.php
> +        return response()->json($submissions);
```suggestion
        return Submission::where('status', SubmissionStatuses::Pending)->paginate();
```

Laravel ya esta preparado para convertir ya sea colecciones o modelos a una respuesta JSON, por lo que no es necesario que pases coleccion por `response()->json()`. 

Por otro lado, podrias tener un scope que ya directamente se encargue de filtrar por status 'pending'.

2023-04-20 15:44 UTC, gianfranco-rocco commented on app/Http/Controllers/GetPendingSubmissionsController.php
> +    public function __invoke(Request $request): JsonResponse
Si no usas el request yo en lo personal no lo inyectaria la dependencia.

2023-04-20 15:44 UTC, gianfranco-rocco commented on routes/api.php
> +    Route::put('/update', UpdatePatientController::class)->name('patient.update');
No queda muy clara esta ruta, no hay forma de saber con exactitud que es lo que hace una ruta que sea `/update`, que es lo que actualiza? Si lo que actualiza es un usuario, entonces deberia de ser `/user/update`, por ejemplo, porque solo `/update` puede ser que actualiza muchas cosas. Si bien podemos leer el codigo, no significa que la ruta no indique a simple vista que es lo que hace.

2023-04-20 15:52 UTC, danielaWaldeck95 commented on app/Http/Controllers/GetPendingSubmissionsController.php
> +        return response()->json($submissions);
En ese caso que use esa response tendria que modificar el tipo del retorno no? Es correcto igual no retornar siempre el mismo tipo de datos? Me tira un error laravel para que retorne algo de tipo LengthAwarePaginator

2023-04-20 15:57 UTC, gianfranco-rocco commented on app/Http/Controllers/GetPendingSubmissionsController.php
> +        return response()->json($submissions);
Si, `paginate()` te retorna una instancia de `LengthAwarePaginator`, que es lo que Laravel te esta diciendo que cambias para el tipo de retorno.
A que te referis con "Es correcto igual no retornar siempre el mismo tipo de datos?"? No entiendo la pregunta

2023-04-20 15:59 UTC, gianfranco-rocco commented
Se puede cambiar el nombre del PR para que sea algo mas informativo? Acostumbremonos a colocar titulos que resumen que es lo que estamos agregando, en lugar del nombre del branch.

2023-04-26 17:26 UTC, gianfranco-rocco requested changes

2023-04-26 17:26 UTC, gianfranco-rocco commented on app/Http/Controllers/GetPendingSubmissionsController.php
> +     * @return \Illuminate\Http\Response
```suggestion
     * @return LengthAwarePaginator
```
Yo en lo personal sacaria el docblock igual.

2023-04-26 17:26 UTC, gianfranco-rocco commented on app/Http/Controllers/GetUserSubmissionsController.php
> +class GetUserSubmissionsController
No te parece redundante el nombre? Todas las submissions siempre pertenencen a un usuario, por lo que me parece que esta demas el `User`. En todos caso si devuelve submissions pertecientes a un paciente, el nombre deberia ser `GetPatientSubmissionsController`, pero si devuelve submissions que un doctor haya tomado, entonces seria `GetDoctorSubmissionsController`. Mi humilde opinion.

2023-04-26 17:26 UTC, gianfranco-rocco commented on routes/api.php
> +
Espacio demas.

2023-10-17 14:14 UTC, closed without merging