feat: as a patient I can update personal information
danielaWaldeck95/big_challenge pull request #6
Opened 2023-02-17 18:05 UTC by danielaWaldeck95

- Create update endpoint.
- Create update patient controller and form request.
- Create permission to update patient's information and assign it to patient role.

- Create feature tests for the following cases
- Not logged
- Not patient
- Missing height
- Missing phone
- Missing weight
- Missing other information
- Successful update

2023-02-17 18:23 UTC, gianfranco-rocco commented on app/Http/Requests/UpdatePatientRequest.php
> +        return Auth::user()->can('update personal information');
En lugar de usar el facade podes hacer: `$this->user()`

2023-02-17 18:30 UTC, gianfranco-rocco requested changes

2023-02-17 18:30 UTC, gianfranco-rocco commented on app/Http/Controllers/UpdatePatient.php
> +class UpdatePatient extends Controller
La herencia de `Controller` esta demas dado que no usas nada de dicha clase.

2023-02-20 17:41 UTC, sojeda commented on tests/Feature/UpdatePatientTest.php
> +});
Hay una mejor manera de escribir esto usando las Factories, porque sino esto lo vas a tener que repetir en muchos Test y no queda lindo.

2023-02-20 17:41 UTC, sojeda commented on tests/Feature/UpdatePatientTest.php
> +});
Mira el ejemplo de Tommy https://github.com/thomasmcculloch2/big_challenge/blob/master/database/factories/UserFactory.php

2023-02-21 14:47 UTC, merged