feat: as a patient I can see my submissions
danielaWaldeck95/big_challenge pull request #8
Opened 2023-02-22 19:09 UTC by danielaWaldeck95

Create endpoint in order to get submissions for loggedin patient. 
Create submission factory and tests.

2023-02-22 19:14 UTC, sojeda approved these changes

2023-02-22 19:16 UTC, gianfranco-rocco requested changes

2023-02-22 19:16 UTC, gianfranco-rocco commented on app/Http/Controllers/IndexSubmissions.php
> +class IndexSubmissions
Raro este nombre, la norma suele ser que si un controller es para obtener registros como en este caso seria submissions es que fuera: GetSubmissionsController

2023-02-22 19:16 UTC, gianfranco-rocco commented on app/Http/Controllers/IndexSubmissions.php
> +        $submissions = $request->user()->submissions()->get();
Si hay 200 submissions vas a mostrar las 200 de una? Faltaria paginacion

2023-02-22 19:16 UTC, gianfranco-rocco commented on app/Http/Controllers/IndexSubmissions.php
> +        return response()->json($response, Response::HTTP_OK);
Por lo general esta bien que simplemente retornes los datos sin necesidad de un mensaje.

2023-02-22 19:16 UTC, gianfranco-rocco commented on database/factories/SubmissionFactory.php
> +            'patient_id' => User::newFactory()->patient()->withInformation()->create(),
Que seria el `withInformation()`?

2023-02-22 20:43 UTC, danielaWaldeck95 commented on database/factories/SubmissionFactory.php
> +            'patient_id' => User::newFactory()->patient()->withInformation()->create(),
Es el paciente que ya ha completado sus datos (teléfono, peso, altura, otros)

2023-02-22 20:44 UTC, danielaWaldeck95 commented on database/factories/SubmissionFactory.php
> +            'patient_id' => User::newFactory()->patient()->withInformation()->create(),
O sea una función en el factory que agrega esa data al paciente

2023-02-23 12:17 UTC, gianfranco-rocco commented on database/factories/SubmissionFactory.php
> +            'patient_id' => User::newFactory()->patient()->withInformation()->create(),
En ese caso no seria mejor llamar al metodo algo como `patientInformation`, por ejemplo? Porque si yo fuera un integrante nuevo que se une al proyecto y leo `withInformation` me veo obligado a meterme en el factory para ver que es lo que hace porque no esta explicito de que informacion estamos hablando. En cambio, si tiene un nombre como el que digo (o alguno de esa indole), ya queda explicito que se lo esta llamando para agregar informacion de paciente, y el unico motivo por el cual meterme en el factory seria ver como se agrega dicha informacion.

2023-02-24 14:45 UTC, gianfranco-rocco commented on app/Http/Controllers/GetSubmissionsController.php
> +        $submissions = $request->user()->submissions()->paginate();
Buenisimo que ahora devueltas la paginacion! Ahora te hago una consulta, la API que hace uso de este controller es unicamente para obtener las submissions de un paciente? Porque segun el codigo se devuelven todas las submissions que le corresponden al usuario logueado (independiente del tipo de usuario que sea), pero el name de la API da a entender que corresponde al contexto del paciente: `patient.submissions.index`. Segun lo veo yo, la API deberia ser agnostica al tipo de usuario, para que cualquiera sea el usuario logueado obtenga las submissions que le correspondan, las cuales en el caso de un paciente serian todas las que haya creado, y en el caso de un doctor seria todas las submissions que haya tomado (logica la cual ya tenes resuelta en la relacion `submissions`).

2023-02-24 14:45 UTC, gianfranco-rocco commented on database/factories/UserFactory.php
> +    public function patientInformation()
No hay return type?

2023-02-24 14:46 UTC, gianfranco-rocco commented on database/factories/SubmissionFactory.php
> +    public function definition()
Return type?

2023-02-24 14:47 UTC, gianfranco-rocco commented on app/Http/Controllers/GetSubmissionsController.php
> +        return response()->json($submissions, Response::HTTP_OK);
El status del response por defecto es 200, por lo que podes optar por no colocar el status dado que en este caso seria redundante.

2023-02-28 20:23 UTC, merged